name: Convert Real-ESRGAN to NCNN

on:
  workflow_dispatch: # manual trigger
    inputs:
      model_url:
        description: 'Direct URL to the Real-ESRGAN .pth model'
        required: true
        default: 'https://github.com/xinntao/Real-ESRGAN/releases/download/v0.3.0/RealESRGAN_x4plus.pth'

jobs:
  convert-to-ncnn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git wget unzip build-essential cmake

    - name: Setup Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install torch torchvision onnx onnxruntime opencv-python numpy

    - name: Clone Real-ESRGAN repository
      run: |
        git clone https://github.com/xinntao/Real-ESRGAN.git
        cd Real-ESRGAN
        pip install -r requirements.txt

    - name: Download model
      run: |
        mkdir -p Real-ESRGAN/weights
        wget -O Real-ESRGAN/weights/model.pth ${{ github.event.inputs.model_url }}

    - name: Convert PyTorch model to ONNX
      run: |
        cd Real-ESRGAN
        python3 basicsr/export_onnx.py --model_path weights/model.pth --output_path weights/model.onnx --half

    - name: Install NCNN tools
      run: |
        git clone https://github.com/Tencent/ncnn.git
        cd ncnn
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        cd ../..
        export PATH=$PWD/ncnn/build/tools:$PATH

    - name: Convert ONNX to NCNN
      run: |
        mkdir -p Real-ESRGAN/ncnn
        onnx2ncnn Real-ESRGAN/weights/model.onnx Real-ESRGAN/ncnn/model.param Real-ESRGAN/ncnn/model.bin

    - name: Upload NCNN model
      uses: actions/upload-artifact@v3
      with:
        name: realesrgan-ncnn-model
        path: Real-ESRGAN/ncnn/
